# -*- coding: utf-8 -*-
"""Web scrapping .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9GN7IGzrJ-4mxGeE5P_-vj03vlyTdpi
"""

import requests

url = requests.get("https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing")

url.status_code

url

import requests

# API URL
url = "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing"

# change limit to 100
params = {
    "start": "1",
    "limit": "100",   #  only 100 coins
    "sortBy": "market_cap",
    "sortType": "desc",
    "convert": "USD"
}

# Get data
response = requests.get(url, params=params)
data = response.json()

coins = data["data"]["cryptoCurrencyList"]

# Lists
names = []
prices = []
change_1h = []
change_24h = []
change_7d = []
market_caps = []
volumes = []
supplies = []

# Extract data
for coin in coins:
    names.append(coin["name"])

    quote = coin["quotes"][0]

    prices.append(quote["price"])
    change_1h.append(quote["percentChange1h"])
    change_24h.append(quote["percentChange24h"])
    change_7d.append(quote["percentChange7d"])
    market_caps.append(quote["marketCap"])
    volumes.append(quote["volume24h"])
    supplies.append(coin["circulatingSupply"])

# Check counts
print("Total coins:", len(names))

# Print output
for i in range(len(names)):
    print(f"\nCoin {i+1}")
    print("Name:", names[i])
    print(f"Price: ${prices[i]:,.2f}")
    print(f"1h%: {change_1h[i]:.2f}%")
    print(f"24h%: {change_24h[i]:.2f}%")
    print(f"7d%: {change_7d[i]:.2f}%")
    print(f"Market Cap: ${market_caps[i]:,.2f}")
    print(f"Volume(24h): ${volumes[i]:,.2f}")
    print(f"Circulating Supply: {supplies[i]:,.2f}")

import requests

url = "https://api.coinmarketcap.com/data-api/v3/cryptocurrency/listing"

all_coins = []
start = 1

#  loop until we get at least 500 coins
while len(all_coins) < 500:
    params = {
        "start": str(start),
        "limit": "100",
        "sortBy": "market_cap",
        "sortType": "desc",
        "convert": "USD"
    }

    response = requests.get(url, params=params)
    data = response.json()

    coins = data["data"]["cryptoCurrencyList"]

    if not coins:
        break

    all_coins.extend(coins)
    print(f"Fetched: {len(all_coins)} coins")

    start += 100

# Take exactly 500
all_coins = all_coins[:500]

# Lists
names, prices, change_1h, change_24h, change_7d = [], [], [], [], []
market_caps, volumes, supplies = [], [], []

# Extract
for coin in all_coins:
    names.append(coin["name"])

    quote = coin["quotes"][0]
    prices.append(quote["price"])
    change_1h.append(quote["percentChange1h"])
    change_24h.append(quote["percentChange24h"])
    change_7d.append(quote["percentChange7d"])
    market_caps.append(quote["marketCap"])
    volumes.append(quote["volume24h"])
    supplies.append(coin["circulatingSupply"])

#  Check
print("\nTotal coins extracted:", len(names))

#  Print first 5
for i in range(500):
    print(f"\nCoin {i+1}")
    print("Name:", names[i])
    print(f"Price: ${prices[i]:,.2f}")
    print(f"1h%: {change_1h[i]:.2f}%")
    print(f"24h%: {change_24h[i]:.2f}%")
    print(f"7d%: {change_7d[i]:.2f}%")
    print(f"Market Cap: ${market_caps[i]:,.2f}")
    print(f"Volume(24h): ${volumes[i]:,.2f}")
    print(f"Circulating Supply: {supplies[i]:,.2f}")

import pandas as pd

df = pd.DataFrame({
    "Name": names,
    "Price": prices,
    "1h%": change_1h,
    "24h%": change_24h,
    "7d%": change_7d,
    "Market Cap": market_caps,
    "Volume(24h)": volumes,
    "Supply": supplies
})

print(df.head())   # first 5 rows

print("Shape:", df.shape)

df["Price"] = df["Price"].apply(lambda x: f"${x:,.2f}")
df["Market Cap"] = df["Market Cap"].apply(lambda x: f"${x:,.2f}")
df["Volume(24h)"] = df["Volume(24h)"].apply(lambda x: f"${x:,.2f}")

df["1h%"] = df["1h%"].apply(lambda x: f"{x:.2f}%")
df["24h%"] = df["24h%"].apply(lambda x: f"{x:.2f}%")
df["7d%"] = df["7d%"].apply(lambda x: f"{x:.2f}%")

df

df.to_csv("coins.csv", index=False)

"""### Import pandas and read the CSV"""

# Read the CSV file
import pandas as pd
df = pd.read_csv("coins.csv")

num_columns = df.shape[1]
print("Number of features (columns):", num_columns)

num_rows = df.shape[0]
print("Number of observations (rows):", num_rows)

print("\nData type of each column:")
print(df.dtypes)

# Convert Supply column to object (string) type
df["Supply"] = df["Supply"].astype(object)

# Verify
print(df.dtypes)

print("\nNumber of missing values in each column:")
print(df.isnull().sum())

"""# Clean Data"""

# Remove $ and , from numeric columns
df["Price"] = df["Price"].str.replace("$", "").str.replace(",", "").astype(float)
df["Market Cap"] = df["Market Cap"].str.replace("$", "").str.replace(",", "").astype(float)
df["Volume(24h)"] = df["Volume(24h)"].str.replace("$", "").str.replace(",", "").astype(float)

# Remove % from percentage columns
df["1h%"] = df["1h%"].str.replace("%", "").astype(float)
df["24h%"] = df["24h%"].str.replace("%", "").astype(float)
df["7d%"] = df["7d%"].str.replace("%", "").astype(float)

df.columns = ["Name", "Price", "Market_Cap", "Volume_24h", "Change_1h", "Change_24h", "Change_7d", "Supply"]
print(df.columns)

numeric_cols = ["Price", "Market_Cap", "Volume_24h", "Change_1h", "Change_24h", "Change_7d", "Supply"]
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

print(df.isnull().sum())

for col in ["Price", "Market_Cap", "Volume_24h"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    df = df[(df[col] >= lower) & (df[col] <= upper)]

"""# EDA"""

import pandas as pd

# Read CSV
df = pd.read_csv("coins.csv")

# Check first few rows
df.head()

# Check data types and null values
df.info()
df.describe()

"""### Univariate analysis
- Numerical columns
"""

df[["Price", "Market Cap", "Volume(24h)", "Supply"]].describe()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# --------- BOXPLOT ---------
plt.figure(figsize=(6,4))
sns.boxplot(x=df["Price"])
plt.title("Boxplot of Price")

# limit x-axis ticks to 10
xmin, xmax = plt.xlim()
plt.xticks(np.linspace(xmin, xmax, 10))

plt.show()


# --------- HISTOGRAM ---------
plt.figure(figsize=(6,4))
sns.histplot(df["Market Cap"], kde=True)
plt.title("Distribution of Market Cap")

# limit x-axis ticks
xmin, xmax = plt.xlim()
plt.xticks(np.linspace(xmin, xmax, 10))

plt.show()


# --------- VIOLIN PLOT ---------
plt.figure(figsize=(6,4))
sns.violinplot(y=df["Volume(24h)"])
plt.title("Violin plot of Volume (24h)")

# limit y-axis ticks
ymin, ymax = plt.ylim()
plt.yticks(np.linspace(ymin, ymax, 10))

plt.show()

"""# categorical columns"""

# Frequency count
df["Name"].value_counts()

# Percentage
df["Name"].value_counts(normalize=True) * 100

#Count Plot

top10 = df["Name"].value_counts().head(10)
sns.countplot(y=df["Name"], order=top10.index)
plt.title("Top 10 Cryptocurrencies")
plt.show()

# Pie chart
top10.plot.pie(autopct='%1.1f%%', figsize=(6,6))
plt.title("Top 10 Cryptocurrencies Percentage")
plt.ylabel("")  # removes extra label
plt.show()

"""### Bivariate/Multivariate Analysis
- continuous vs continuous
"""

# Remove $ and commas, then convert to float
cols = ["Price", "Market Cap", "Volume(24h)", "Supply"]

for col in cols:
    df[col] = df[col].astype(str)  # ensure string
    df[col] = df[col].str.replace(r'[\$,]', '', regex=True)  # remove $ and ,
    df[col] = pd.to_numeric(df[col], errors='coerce')  # convert to float

sns.scatterplot(x=df["Price"], y=df["Market Cap"])
plt.title("Price vs Market Cap")
plt.show()

# Correlation matrix
corr = df[["Price", "Market Cap", "Volume(24h)", "Supply"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""- continuous vs categorical"""

df.groupby("Name")["Price"].mean().sort_values(ascending=False)

top10 = df.sort_values("Price", ascending=False).head(10)

sns.barplot(x="Price", y="Name", data=top10)
plt.title("Top 10 Cryptocurrencies by Price")
plt.show()

"""- Categorical vs Categorical"""

# Create price tiers
def price_tier(price):
    if price < 1:
        return "Low"
    elif price < 100:
        return "Medium"
    else:
        return "High"

df["Price_Tier"] = df["Price"].apply(price_tier)
df["Price_Tier"].value_counts()

pd.crosstab(df["Name"], df["Price_Tier"])

top10 = df["Name"].value_counts().head(10).index
df_top10 = df[df["Name"].isin(top10)]

pd.crosstab(df_top10["Name"], df_top10["Price_Tier"]) \
    .plot(kind='bar', stacked=True, figsize=(12,6))

plt.title("Price Tier of Top 10 Coins")
plt.xlabel("Coin Name")
plt.ylabel("Count")
plt.show()